### ISSUE TITLE
Add notifications to deploy process

### ISSUE THREAD

**Issue by joncamfield** [the-engine-room/level-up#172]
Travis supports multiple types of outbound notifications on build status: https://docs.travis-ci.com/user/notifications/ - most useful for LU is probably sending pings to the LU-focused lists on dev deploys, and possibly to additional, more public lists on live deploys:

I think this, added to the dev and live conditional deploy sections, should always email the contributor plus levelup@riseup.net on any changes to dev or live, and we can also push emails to specific other lists on successful changes to the live site if we like.  We'll have to figure out how to add or whitelist the alert user if we want to send to listservs:

Dev:

```
# privately announce all changes to dev
notifications:
  email:
    recipients:
      - levelup@riseup.net
    on_success: always # default: change
    on_failure: always # default: always
```

Live:

```
# privately announce all changes to live
notifications:
email:
    recipients:
      - levelup@riseup.net
      - ???
    on_success: change # default: change
    on_failure: always # default: always

# Publicly announce successful changes to live
  email:
    recipients:
      - levelup@lists.riseup.net
      - ???
    on_success: change # default: change
    on_failure: never # default: always

```
